import { Router } from "express";
import { healthRouter } from "./health";
import { authRouter } from "./auth";
import { adminRouter } from "./admin";
import { agenciesRouter } from "./agencies";
import { auctionsRouter } from "./auctions";
import { dashboardsRouter } from "./dashboards";
import { lotsRouter } from "./lots";
import { notificationsRouter } from "./notifications";
import { proposalsRouter } from "./proposals";
import { solicitationsRouter } from "./solicitations";
import { chatRouter } from "./chat";
import { contactRouter } from "./contact";
import { publicStatsRouter } from "./publicStats";

export const router = Router();
router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/admin", adminRouter);
router.use("/agencies", agenciesRouter);
router.use("/auctions", auctionsRouter);
router.use("/dashboards", dashboardsRouter);
router.use("/lots", lotsRouter);
router.use("/notifications", notificationsRouter);
router.use("/proposals", proposalsRouter);
router.use("/solicitations", solicitationsRouter);
router.use("/chat", chatRouter);
router.use("/contact", contactRouter);
router.use("/public", publicStatsRouter);
